# Generated by Django 5.1.7 on 2025-03-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='check_in',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
