# Generated by Django 5.1.7 on 2025-03-25 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_usercreation_delete_attendancerecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercreation',
            old_name='check_out',
            new_name='user_created_time',
        ),
    ]
