# Generated by Django 5.1.7 on 2025-03-25 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_rename_check_out_usercreation_user_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercreation',
            name='user_created_time',
        ),
        migrations.AlterField(
            model_name='usercreation',
            name='user_created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
