# Generated by Django 5.1.7 on 2025-04-05 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_attendancerecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
        migrations.RenameField(
            model_name='usercreation',
            old_name='user_created_date',
            new_name='user_updated_date',
        ),
    ]
