# Generated by Django 5.1.7 on 2025-04-06 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_usercreation_user_updated_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercreation',
            name='user_updated_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='usercreation',
            name='user_updated_time',
            field=models.TimeField(),
        ),
    ]
